version: "3"

services:
  app:
    build: .
    depends_on:
      - postgres
      # - mongo
      - redis
    ports:
      - "3000:3000"
      - "5432:5432"
      # - "27017:27017"
      - "6379:6379"
    volumes:
      - .:/usr/app

  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=meetapp

  # mongo:
  #   image: mongo:
  #   ports:

  redis:
    image: redis:5-alpine
